name: Bug Report
description: Report something broken
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true